=== liyanaa18/XML-technologies-for-semantic-web/XML - project/XML2023_ProjectNo14/recipesSchema.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com"
elementFormDefault="qualified">

    <xs:element name="cookingRecipesCatalogue">
        <xs:complexType>
    		<xs:sequence>
    			<xs:element ref="regions" />
    			<xs:element ref="techniquesList" />
                <xs:element ref="mealList"/>
                <xs:element ref="recipes"/>
    		</xs:sequence>
    	</xs:complexType>
         
         
        <xs:key name="mealKey">
     		<xs:selector xpath="cookingRecipesCatalogue/mealList/meal"/>
     		<xs:field xpath="@type"/>
        </xs:key>
    
        <xs:keyref name="mealRefToKey" refer="mealKey">
            <xs:selector xpath="cookingRecipesCatalogue/recipes/recipe/meal"/>
            <xs:field xpath="@typeRef"/>
        </xs:keyref>
        
        
        
        <xs:key name="regionKey">
     		<xs:selector xpath="cookingRecipesCatalogue/regions/region"/>
     		<xs:field xpath="@ID"/>
        </xs:key>
    
        <xs:keyref name="regionRefToKey" refer="regionKey">
            <xs:selector xpath="cookingRecipesCatalogue/recipes/recipe"/>
            <xs:field xpath="@regionRef"/>
        </xs:keyref>
        
        
        <xs:key name="techniqueKey">
     		<xs:selector xpath="cookingRecipesCatalogue/techniquesList/technique"/>
     		<xs:field xpath="@name"/>
        </xs:key>
    
        <xs:keyref name="techniqueRefToKey" refer="techniqueKey">
            <xs:selector xpath="cookingRecipesCatalogue/recipes/recipe/techniques/technique"/>
            <xs:field xpath="@techniqueRef"/>
        </xs:keyref>
        
    </xs:element>
    
    <xs:element name="recipes">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="recipe" maxOccurs="unbounded" minOccurs="0"/>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
      
    <xs:element name="recipe">
        <xs:complexType mixed="true">
        	<xs:sequence>
        		<xs:element ref="name" />
        		<xs:element ref="image" minOccurs="0"/>
                <xs:element ref="origin" minOccurs="0"/>   
        		<xs:element ref="author" />     
        		<xs:element ref="kitchen" />
        		<xs:element ref="meal"/>
        		<xs:element ref="ingredients" />         
        		<xs:element ref="cookingTime" />
        		<xs:element ref="process" />
        		<xs:element ref="techniques" minOccurs='0' />
        		<xs:element ref="servingMethod" />
        		<xs:element ref="matchDrinks" />
        		<xs:element ref="medicalParameters" />
        	</xs:sequence>
            <xs:attribute name="regionRef" type="xs:decimal" use='required'/>
        	<xs:attribute name="ID" type="xs:decimal" use='required'/>
        </xs:complexType>
    </xs:element>
      
    <xs:element name="name" type="xs:string" />
    <xs:element name="origin" type="xs:string" />
    <xs:element name="author" type="xs:string" />
    <xs:element name="cookingTime" type="xs:decimal" />
      
    <xs:element name="image">
    	<xs:complexType>	
    		<xs:attribute name="source" type="xs:ENTITY" use='required'/>
    	</xs:complexType>
    </xs:element>
      
    <xs:element name="kitchen">
        <xs:simpleType>
            	<xs:restriction base="xs:string">
              		<xs:enumeration value="Веган"/>
                   	<xs:enumeration value="Месна"/>
                    <xs:enumeration value="Вегетарианска"/>
            	</xs:restriction>
          </xs:simpleType>
    </xs:element>
    	
    <xs:element name="meal">
    	<xs:complexType>
    		<xs:attribute name="typeRef" type="xs:integer" use='required'/>
    	</xs:complexType>
    </xs:element>
    
    <xs:simpleType name="mealRefType">
          <xs:restriction base="xs:string">
            	<xs:enumeration value="Предястие"/>
                <xs:enumeration value="Основно"/>
                <xs:enumeration value="Десерт"/>
          </xs:restriction>
     </xs:simpleType>
     
     <xs:element name="ingredients">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="list" />
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>

    <xs:element name="list">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="product" maxOccurs='unbounded'/>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="product">
    	<xs:complexType mixed="true">
    		<xs:attribute name="quantity" type="xs:string"/>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="process">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="step" maxOccurs='unbounded'/>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="step" type="xs:string" />
    <xs:element name="servingMethod" type="xs:string" />
     
    <xs:element name="matchDrinks">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="drink" maxOccurs='unbounded'/>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="drink" type="xs:string" />
    
    <xs:element name="medicalParameters">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="descriptionMedicalParameters" />
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="descriptionMedicalParameters" type="xs:string" />

	<xs:element name="techniques">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="technique" maxOccurs='unbounded'>
				    <xs:complexType>
					    <xs:attribute name="techniqueRef" type='techniqueRefType' use='required'/>
				    </xs:complexType>
			    </xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    
    <xs:element name="technique">
    	<xs:complexType>
    		<xs:attribute name="techniqueRef" type='techniqueRefType' use='required'/>
    	</xs:complexType>
    </xs:element>
    
    <xs:simpleType name="techniqueRefType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Задушаване"/>
            <xs:enumeration value="Пържене"/>
            <xs:enumeration value="Печене"/>
            <xs:enumeration value="Сотиране"/>
            <xs:enumeration value="Бланширане"/>
            <xs:enumeration value="Варене"/>
            <xs:enumeration value="Застройване"/>
            <xs:enumeration value="Паниране"/>
        </xs:restriction>
    </xs:simpleType>
    
    
    
    <xs:element name="regions">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="region" minOccurs='0' maxOccurs='6'/>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="region">
    	<xs:complexType>
    		<xs:attribute name="ID" type='xs:decimal' use='required'/>
    		<xs:attribute name="title" type='regionTitleType' use='required'/>
    	</xs:complexType>
    </xs:element>    
    
	<xs:simpleType name="regionTitleType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Югозападен"/>
 			<xs:enumeration value="Южен Централен"/>
 			<xs:enumeration value="Северозападен"/>
			<xs:enumeration value="Югоизточен"/>
 			<xs:enumeration value="Североизточен"/>
			<xs:enumeration value="Северен централен район"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="techniquesList">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="technique" minOccurs='0' maxOccurs='8'>
					<xs:complexType mixed="true">
						<xs:sequence>
							<xs:element name="description" type="xs:string" />
						</xs:sequence>
						<xs:attribute name="name" type='techniqueRefType' use='required'/>
					</xs:complexType>
			    </xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
   
    
      
    <xs:element name="mealList">
    	<xs:complexType>
    		<xs:sequence>
				<xs:element name="meal" maxOccurs="3" minOccurs="0">
					<xs:complexType>
    		            <xs:attribute name="type" type="xs:integer" use='required'/>
                        <xs:attribute name="mealTitle" type="mealRefType" use='required'/>
    	            </xs:complexType>
				</xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>  	


</xs:schema>

=== liyanaa18/XML-technologies-for-semantic-web/XML - project/XML2023_ProjectNo14/cookingRecipesCatalogue.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE cookingRecipesCatalogue [
	<!NOTATION JPEG SYSTEM "image/jpeg">
	<!ENTITY shopska-salata SYSTEM "./images/shopska-salata.jpg" NDATA JPEG>
	<!ENTITY zelnik SYSTEM "./images/zelnik.jpg" NDATA JPEG>
	<!ENTITY sour-cabbage SYSTEM "./images/sour-cabbage.jpg" NDATA JPEG>
	<!ENTITY patatnik SYSTEM "./images/patatnik.jpg" NDATA JPEG>
	<!ENTITY bel-muj SYSTEM "./images/bel-muj.jpg" NDATA JPEG>
	<!ENTITY banitsa SYSTEM "./images/banitsa.jpg" NDATA JPEG>
	<!ENTITY lutika SYSTEM "./images/lutika.jpg" NDATA JPEG>
]>

<?xml-stylesheet type="text/xsl" href="cookingRecipesCatalogue.xsl"?>

<cookingRecipesCatalogue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="recipesSchema.xsd">
	<regions>
		<region ID="1" title="Югозападен"/>
		<region ID="2" title="Южен Централен"/>
		<region ID="3" title="Северозападен"/>
	</regions>
	
	<techniquesList>
		<technique name = "Варене">
			<description>Варенето представлява равномерно нагряване на хранителните продукти до състояние на 
			кулинарна готовност при пълно потапяне в течност (вода, бульон, мляко, захарен сироп) или среда, 
			наситена с водна пара.</description>
		</technique>
		
		<technique name = "Пържене">
			<description>Процес, при който хранителните продукти се довеждат до състояние на готовност чрез нагряване в мазнина с температура 150-190С, 
			като се получава специфична коричка по повърхността на продукта.</description>
		</technique>
		
		<technique name = "Печене">
			<description>Процес, при който хранителните продукти 
			се нагряват с горещ въздух (100-300 С) или с лъчиста енергия. </description>
		</technique>
		
		<technique name = "Задушаване">
			<description>Процес, при който продуктите се нагряват в собствен сок или в малко количество течност до състояние на кулинарна готовност.</description>
		</technique>
	</techniquesList>
	
	<mealList> 
		<meal type="10" title = "Предястие"/>
		<meal type="11" title = "Основно"/>  
		<meal type="12" title = "Десерт"/> 
	</mealList>

	<recipes>
		<recipe ID="1000" regionRef="1">
			<name>Шопска салата</name>
			<image source="shopska-salata" />
			<author>Зорица</author>
			<kitchen>Вегетарианска</kitchen> 
			<meal typeRef="10" />	
			<ingredients>
				<list>
					<product quantity = "400гр">домати</product>
					<product quantity = "250гр">краставици</product>
					<product quantity = "1 бр.">зелени печени чушки</product>
					<product quantity = "1 глава">кромид лук</product>
					<product quantity = "200 г">краве сирене</product>
					<product quantity = "1/2 връзка">наситнен магданоз</product>
					<product>оцет</product>
					<product>олио</product>
					<product>сол</product>
					<product>маслини</product>
					<product>зелени чушки - за украса</product>
					<product quantity = "няколко стръкчета за гарниране">магданоз</product>
				</list>
			</ingredients>
			<cookingTime>10</cookingTime>
			<process>
				<step>Доматите се нарязват на кубчета.</step>
				<step>Краставиците се обелват и нарязват на кръгчета или полумесеци.</step>
				<step>Чушката се нарязва на лентички.</step>
				<step>Лукът и магданоза се наситняват.</step>
				<step>Всичко се прехвърля в купа и посолява със сол, оцет и олио на вкус.</step>
				<step>Разбърква се и салатата се разпределя в чинии, като се оформя на купчинка.</step>
				<step>Отгоре се поръсва обилно с настърганото краве сирене.</step>
				<step>Украсява се с маслина, зелена чушка и клончета магданоз.</step>
			</process>
			<servingMethod>
				Сервира се студена, аранжирана с маслини и стръкче магданоз.
			</servingMethod>
			<matchDrinks>
				<drink>българска ракия</drink>
				<drink>вино Червен мискет</drink>
				<drink>вино Блан де ноар</drink>
			</matchDrinks>
			<medicalParameters>
				<descriptionMedicalParameters>Калиевите соли в домата помагат на сърцето и са безценни при анемия и заради пурините,които имат се препоръчват при артрит и атеросклероза. 
				Помагат още при песъчинки в бъбреците, полезни са за стомаха и влияят добре на диабетиците. 
				При грип и инфекции лукът е сред задължителните лекарства, напомнят диетолозите. 
				Освен, че сваля холестерола и помага при атеросклероза, стимулира и стомаха - възбужда апетита, засилва отделянето на храносмилателни сокове 
				и помага за по-доброто усвояване на хранителните вещества. </descriptionMedicalParameters>
			</medicalParameters>
		</recipe>
		
		<recipe ID="1001" regionRef="1">
			<name>Традиционен зелник</name>
			<image source="zelnik" />
			<origin> Кюстендилският край</origin>
			<author>Ники</author>
			<kitchen>Вегетарианска</kitchen>
			<meal typeRef = "11"></meal>
			<ingredients>
				<list>
					<product quantity = "350 гр">брашно</product>
					<product quantity = "100 гр">масло</product>
					<product quantity = "3 бр.">яйца</product>
					<product quantity = "500 гр">кисело мляко</product>
					<product quantity = "1 ч.л. ">сода</product>
					<product quantity = "1 ч.л. ">сол</product>
					<product quantity = "1/2 ч.л. ">захар</product>
			
					<product>копър</product>
					<product>черен пипер</product>
					<product quantity = "500 гр">зеле</product>
					<product quantity = "1 бр.">лук</product>
					<product>сол</product>
					<product>чили - по желание</product>
				</list>
			</ingredients>
			<cookingTime>80</cookingTime>
			<process>
				<step>Нарязваме си зелето и лука на ситно. </step>
				<step>В дълбок тиган задушаваме първо лука, след това добавяме зелето. </step>
				<step>Добавяме солта, черния пипер и за обичащите пикантно може да добавите сухо, едро чили. </step>
				<step>Задушаваме зелето до прозрачност.</step>
				<step>Добавяме нарязания на ситно копър.</step>
				<step>В купа си разбиваме яйцата със солта и захарта.</step>
				<step>Добавяме разтопеното масло и киселото мляко.</step>
				<step>Накрая добавяме пресятото брашно със содата.</step>
				<step>Разбъркваме добре, тестото трябва да се получи като гъста заквасена сметана. </step>
				<step>В тава си слагаме хартия за печене, намазняваме и сипваме част от тестото, след това 
					плънката и отгоре пак тесто, също така може да смесим тестото с плънката и да добавим сместа в тавата. 
				</step>
				<step>Печем зелника на 180 градуса</step>
			</process>	

			<techniques>
				<technique techniqueRef="Задушаване" />
				<technique techniqueRef="Печене" />
			</techniques>

			<servingMethod>
				Зелникът се сервира топъл и нарязан на триъгълни парчета
			</servingMethod>
			<matchDrinks>
				<drink>бира</drink>
				<drink>айрян</drink>
			</matchDrinks>
			<medicalParameters>
				<descriptionMedicalParameters>Зелето има благоприятен ефект върху храносмилателната система, стимулира метаболизма, нежно почиства организма, 
				премахва токсините и холестерола. Зелето е от съществено значение по време на бременност. 
				То помага за премахване на излишни течности от тялото и премахване на отоци, което е важно за много бъдещи майки през последното тримесечие.</descriptionMedicalParameters>
			</medicalParameters>
		</recipe>
		
		<recipe ID="1002" regionRef="1">
			<name>Вариво с кисело зеле</name>
			<image source="sour-cabbage" />
			<origin>Пернишки край</origin>
			<author>Гергана Георгиева</author>
			<kitchen>Месна</kitchen>
			<meal typeRef = "11"></meal>
			<ingredients>
				<list>
					<product quantity = "1 голяма зелка">кисело зеле</product>
					<product quantity = "800 гр">свинско месо</product>
					<product quantity = "200 гр">бекон</product> 
					<product quantity = "1 пълна с.л.">свинска мас</product>
					<product quantity = "5 с.л.">олио</product>
					<product quantity = "1 с.л.">червен пипер</product>
					<product>сол</product>
					<product quantity = "1 глава">чесън</product>
					<product>вода</product>
				</list>
			</ingredients>
			<cookingTime>210</cookingTime>
			<process> 
				<step>Нарязваме зелето на парченца. Нарязваме и месото на късчета, а бекона на дребничко.</step>
				<step>Подреждаме в дълбока тенджера един пласт зеле, след това слагаме месото и бекона, и покриваме с останалото зеле.</step>
				<step>Слагаме свинската мас, олиото, червения пипер, сол ако е необходимо.</step>
				<step>Почистваме една глава чесън от външната люспа и коренчетата, измиваме я и я пъхаме в зелето.</step>
				<step>Заливаме съдържанието в тенджерата с топла вода, захлупваме с капак и слагаме да се вари около два часа и половина, като от време на време разбъркваме.</step> 
				<step>Когато вече е готово, изваждаме чесъна.</step>
			</process>

			<techniques>
				<technique techniqueRef="Варене" />
			</techniques>

			<servingMethod>
				Варивото с кисело зеле се сервира топъл.
			</servingMethod>

			<matchDrinks>
				<drink>вино</drink>
				<drink>греяната ракия</drink>
			</matchDrinks>

			<medicalParameters>
				<descriptionMedicalParameters>Чесънът може да намали кръвното налягане и риска от развитието на рак на дебелото черво. 
				Ефективен е срещу гъбички, може да прочисти натрупванията в артериите и помага за контрола върху астмата. Също така се бори с настинки. 
				Киселото зеле подобрява работата на стомашно-чревния тракт, нормализира храносмилането, понижава нивото на холестерола в организма и подобрява 
				работата на сърдечно съдовата система. В него се съдържа витамин U, който прекрасно помага за справяне със зимната депресия, възстановява нервната система и 
				повишава устойчивостта на стрес. В сравнение с останалите видове месо, свинското е сред онези, които са особено богати на протеини. 
				А маста и сланината от прасето съдържат арахидонова киселина и селен, които ни предпазват от депресия и способстват за обновяването на клетките ни. 
				Свинското е изключително богато на витамини от В групата, и то в значително по-големи количества в сравнение с останалите меса.
